server:
  port: 12376

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: ENC(hFaYf1WbBH6ORu0fQdDItKkOvEncMjea/lkiOtCrF/o/hC4rC/GXb8kRkimkCRjVl7lAMViKFdQRoXeH/vkMWePY5c2rbIcS63VPD6jHHKJ2oMfA/yMQyR82lwK8QUzQ80illLAeNO1SbD+u1jtaAg==)
    username: ENC(869OCI47yhuVlUk8ITjnfA==)
    password: ENC(5ozwKMwiSAffkh2+NG++ptjDxBesCFsVp1m91Wa/1cw=)
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  redis:
    port: 6379
    host: ENC(NaLc63TtijboI5t9wYpk2g==)
logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace

jwt:
  secret: ENC(s9MlePyeyjYhoNHUgwZ36VetjiEA5g9CS+nIBkHS1yvm2raaXeF9NRsUHDnHs4wXDxoMfDFRiBR71vAAJVbnMahLa4X8B66T)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

refresh-token-cookie:
  path: /api/token
  name: refresh-token
  day: 30

autocomplete:
  suffix: '*'
  limit: 5